#pragma once
#include "SDK/Packet/Packet.h"
#include "SDK/Packet/PacketIds.h"

class DisconnectPacket final : public Packet {
public:
    const enum class DisconnectFailReason : uint32_t {
        Unknown = 0,
        CantConnectNoInternet = 1,
        NoPermissions = 2,
        UnrecoverableError = 3,
        ThirdPartyBlocked = 4,
        ThirdPartyNoInternet = 5,
        ThirdPartyBadIP = 6,
        ThirdPartyNoServerOrLocked = 7,
        VersionMismatch = 8,
        SkinIssue = 9,
        InviteSessionNotFound = 10,
        EduLevelSettingsMissing = 11,
        LocalServerNotFound = 12,
        LegacyDisconnect = 13,
        UserLeaveGameAttempted = 14,
        PlatformLockedSkinsError = 15,
        RealmsWorldUnassigned = 16,
        RealmsServerCantConnect = 17,
        RealmsServerHidden = 18,
        RealmsServerDisabledBeta = 19,
        RealmsServerDisabled = 20,
        CrossPlatformDisallowed = 21,
        CantConnect = 22,
        SessionNotFound = 23,
        ClientSettingsIncompatibleWithServer = 24,
        ServerFull = 25,
        InvalidPlatformSkin = 26,
        EditionVersionMismatch = 27,
        EditionMismatch = 28,
        LevelNewerThanExeVersion = 29,
        NoFailOccurred = 30,
        BannedSkin = 31,
        Timeout = 32,
        ServerNotFound = 33,
        OutdatedServer = 34,
        OutdatedClient = 35,
        NoPremiumPlatform = 36,
        MultiplayerDisabled = 37,
        NoWifi = 38,
        WorldCorruption = 39,
        NoReason = 40,
        Disconnected = 41,
        InvalidPlayer = 42,
        LoggedInOtherLocation = 43,
        ServerIdConflict = 44,
        NotAllowed = 45,
        NotAuthenticated = 46,
        InvalidTenant = 47,
        UnknownPacket = 48,
        UnexpectedPacket = 49,
        InvalidCommandRequestPacket = 50,
        HostSuspended = 51,
        LoginPacketNoRequest = 52,
        LoginPacketNoCert = 53,
        MissingClient = 54,
        Kicked = 55,
        KickedForExploit = 56,
        KickedForIdle = 57,
        ResourcePackProblem = 58,
        IncompatiblePack = 59,
        OutOfStorage = 60,
        InvalidLevel = 61,
        DisconnectPacketDeprecated = 62,
        BlockMismatch = 63,
        InvalidHeights = 64,
        InvalidWidths = 65,
        ConnectionLostDeprecated = 66,
        ZombieConnection = 67,
        Shutdown = 68,
        ReasonNotSet = 69,
        LoadingStateTimeout = 70,
        ResourcePackLoadingFailed = 71,
        SearchingForSessionLoadingScreenFailed = 72,
        ConnProtocolVersion = 73,
        SubsystemStatusError = 74,
        EmptyAuthFromDiscovery = 75,
        EmptyUrlFromDiscovery = 76,
        ExpiredAuthFromDiscovery = 77,
        UnknownSignalServiceSignInFailure = 78,
        XblJoinLobbyFailure = 79,
        UnspecifiedClientInstanceDisconnection = 80,
        ConnSessionNotFound = 81,
        ConnCreatePeerConnection = 82,
        ConnIce = 83,
        ConnConnectRequest = 84,
        ConnConnectResponse = 85,
        ConnNegotiationTimeout = 86,
        ConnInactivityTimeout = 87,
        StaleConnectionBeingReplaced = 88,
        RealmsSessionNotFound = 89,
        BadPacket = 90,
        ConnFailedToCreateOffer = 91,
        ConnFailedToCreateAnswer = 92,
        ConnFailedToSetLocalDescription = 93,
        ConnFailedToSetRemoteDescription = 94,
        ConnNegotiationTimeoutWaitingForResponse = 95,
        ConnNegotiationTimeoutWaitingForAccept = 96,
        ConnIncomingConnectionIgnored = 97,
        ConnSignalingParsingFailure = 98,
        ConnSignalingUnknownError = 99,
        ConnSignalingUnicastDeliveryFailed = 100,
        ConnSignalingBroadcastDeliveryFailed = 101,
        ConnSignalingGenericDeliveryFailed = 102,
        EditorMismatchEditorWorld = 103,
        EditorMismatchVanillaWorld = 104,
        WorldTransferNotPrimaryClient = 105,
        ServerShutdown = 106,
        GameSetupCancelled = 107,
        GameSetupFailed = 108,
        NoVenue = 109,
        ConnSignallingSignInFailed = 110,
        SessionAccessDenied = 111,
        ServiceSignInIssue = 112,
        ConnNoSignalingChannel = 113,
        ConnNotLoggedIn = 114,
        ConnClientSignallingError = 115,
        SubClientLoginDisabled = 116,
        DeepLinkTryingToOpenDemoWorldWhileSignedIn = 117,
        AsyncJoinTaskDenied = 118,
        RealmsTimelineRequired = 119,
        GuestWithoutHost = 120,
        FailedToJoinExperience = 121,
    };

public:
    DisconnectPacket();
    explicit DisconnectPacket(std::string_view packetData);

    ~DisconnectPacket() {};

    DisconnectFailReason reason;
    bool hideDisconnectReason;
    std::optional<std::string> message;
    std::optional<std::string> filteredMessage;

    [[nodiscard]] std::string serialize() const override;

public:
    inline static const char* packetName = "DisconnectPacket";
    static constexpr MinecraftPacketIds packetId = MinecraftPacketIds::Disconnect;
    static constexpr int packetIdAsInt = static_cast<int>(packetId);
};
